let div = document.createElement('div');
div.className = "mainnav";
div.innerHTML = '<div id ="logo-collapse"><a href="index.html"><img src="img/patt2.png" /></a></div>'
  + '<nav>'
  + '<ul>'
  + '<li id="link-home"><a href="index.html">Acceuil</a></li>'
  + '<li class="menu-deroulant">'
  + '<span>Le Web</span>'
  + '<ul class="sous-menu">'
  + '<li><a href="the-web.html">C\'est quoi ?</a></li>'
  + '<li><a href="mediaweb.html">Un média ?</a></li>'
  + '<li><a href="canaldistributionweb.html">Un canal ?</a></li>'
  + '</ul>'
  + '</li>'
  + '<li class="menu-deroulant">'
  + '<span>Infos</span>'
  + '<ul class="sous-menu">'
  + '<li><a href="step-concept-site.html">Les étapes</a></li>'
  + '<li><a href="mes-competences.html">Compétences</a></li>'
  + '</ul>'
  + '</li>'
  + '<li class="menu-deroulant">'
  + '<span>Services</span>'
  + '<ul class="sous-menu">'
  + '<li><a href="services-concept-site.html">Conception</a></li>'
  + '<li><a href="services-concept-site-dns-host.html">Hébergement</a></li>'
  + '<li><a href="services-concept-site-web-solution-main.html">Solutions</a></li>'
  + '<li><a href="services-concept-site-benefits.html">Avantages</a></li>'
  + '</ul>'
  + '</li>'
  + '</ul>'
  + '</nav>';

document.getElementById("wrapper").append(div);